import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News portal || Mezbah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        <div className="lg:ml-[15%] ml-0 pb-[120px] lg:pb-0 lg:pt-16 md:mt-10 mt-5 px-3">
          {children}
        </div>
      </body>
    </html>
  );
}
